---
pagetitle: "R Tutorial"
output: 
  html_document:
    toc: FALSE
---

<br>

## **About**

このページでは、R言語を用いたIR（主に研究力分析）の事例を、備忘録も兼ねて紹介していきます。IRでは大規模データを扱うことが多く、RやPythonといったプログラミング言語を活用することにより、作業時間の短縮、正確性、再現性の向上等が見込めます。もし、Rにご興味をお持ちの方がいらっしゃいましたら、少しでも参考になりましたら幸いです。なお、本ページをご覧になるにあたり、以下の点にご留意ください。

  - 本サイトでは、主に分析・可視化手法/コードの紹介に焦点を当てており、結果の数字にあまり意味はありません。<br>
  - 必ずしも最適な分析・可視化方法・コードを紹介しているわけではありません（他に良い方法があれば是非シェアしてください）。<br>
  - R言語やパッケージのバージョンの違いにより、お手元の実行環境によっては必ずしも結果を再現できないことがあります。私の実行環境については[こちら](session_info.html)をご参照ください。

# {.tabset}

## **科研費関係**
ここでは主に[KAKENデータベース](https://kaken.nii.ac.jp)を活用したデータ処理事例を紹介していきます。基本的にはダウンロード可能なcsvファイルを用いたデータの前処理や集計、可視化までを行なっていきますが、最終的にはAPIの活用方法やXMLファイルの操作までを紹介できればと考えています。

  - [データの要約（１）：配分額と採択件数の集計](kaken_summary_01.html)
  - [データの要約（２）：配分額と採択件数を相対的に表現](kaken_summary_02.html)
  - [データの要約（３）：配分額を年度別に集計](kaken_summary_03.html)
  - [データのクリーニング（１）：研究機関列の整理](kaken_cleaning_01.html)
  - [データのクリーニング（２）：研究代表者列から情報抽出](kaken_cleaning_02.html)
  - [データのクリーニング（３）：研究分担者列の展開](kaken_cleaning_03.html)
  - [データのクリーニング（４）：審査区分列の整理](kaken_cleaning_04.html)
  - [データの可視化（１）：配分額を棒グラフで可視化](kaken_plot_01.html)
  - [データの可視化（２）：配分額の年度推移を折れ線グラフで可視化](kaken_plot_02.html)
  - [データの可視化（３）：配分額と件数を散布図で可視化](kaken_plot_03.html)
  - [データの可視化（４）：配分額を円グラフで可視化](kaken_plot_04.html)
  - [データの可視化（５）：配分額をヒストグラムで可視化](kaken_plot_05.html)
  - [データの可視化（６）：配分額を箱ひげ図で可視化](kaken_plot_06.html)
  - [データの可視化（７）：審査区分ごとの配分額をレーダーチャートで可視化](kaken_plot_07.html)
  - [データの可視化（８）：条件を変えて繰り返しグラフを描画](kaken_plot_08.html)
  - [データの可視化（９）：条件を変えて全てのグラフを保存](kaken_plot_09.html)

